version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "1606:1606"
    volumes:
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
